	const_def
	const MON_NONE             ;  00
	const MON_NEKHBET          ;  01
	const MON_TATARIMOKKE      ;  02
	const MON_HIPPOU           ;  03
	const MON_DEVA             ;  04
	const MON_BASTET           ;  05
	const MON_KOTODAMA         ;  06
	const MON_UNICORN          ;  07
	const MON_RUKH             ;  08
	const MON_HOUOU            ;  09
	const MON_DEVA_LORD        ;  0A
	const MON_KOMAINU          ;  0B
	const MON_NEKOSHOGUN       ;  0C
	const MON_HORUS            ;  0D
	const MON_PEGASUS          ;  0E
	const MON_SHISA            ;  0F
	const MON_OKITSUNE         ;  10
	const MON_SUZAKU           ;  11
	const MON_BYAKKO           ;  12
	const MON_YATSUFUSA        ;  13
	const MON_ITZAMNA          ;  14
	const MON_QUETZALCOATL     ;  15
	const MON_BARONG           ;  16
	const MON_GARUDA           ;  17
	const MON_CANCER           ;  18
	const MON_TANUKI_FOOD      ;  19
	const MON_GENBU            ;  1A
	const MON_RANDA            ;  1B
	const MON_KIRIN            ;  1C
	const MON_QINGNIUGUAI      ;  1D
	const MON_HAIRY_JACK       ;  1E
	const MON_NEKOMATA         ;  1F
	const MON_AAMAN            ;  20
	const MON_SHURA            ;  21
	const MON_ANZU             ;  22
	const MON_BAHANG           ;  23
	const MON_WATCH_BUNNY      ;  24
	const MON_SHURA_LORD       ;  25
	const MON_ARACHNE          ;  26
	const MON_STYMPHALIAN      ;  27
	const MON_HIPPOGRYPH       ;  28
	const MON_ANUBIS           ;  29
	const MON_ISIS             ;  2A
	const MON_BATHIN           ;  2B
	const MON_TAKSAKA          ;  2C
	const MON_NUE              ;  2D
	const MON_AZOTH            ;  2E
	const MON_BLACK_ROGER      ;  2F
	const MON_RAHAB            ;  30
	const MON_TITAN            ;  31
	const MON_MAMMON           ;  32
	const MON_TSUKUYOMI        ;  33
	const MON_SUSANOO          ;  34
	const MON_VAN              ;  35
	const MON_SCATHACHA        ;  36
	const MON_KRAKEN           ;  37
	const MON_VAN_LORD         ;  38
	const MON_NISROC           ;  39
	const MON_WATCHER          ;  3A
	const MON_NIKE             ;  3B
	const MON_GURIGORI         ;  3C
	const MON_ZEPAR            ;  3D
	const MON_ANGEL            ;  3E
	const MON_KOAKUMA          ;  3F
	const MON_SKULL_CLOWN      ;  40
	const MON_PRINCE           ;  41
	const MON_RAZIEL           ;  42
	const MON_ARCHE            ;  43
	const MON_EXUSIA           ;  44
	const MON_POWER            ;  45
	const MON_VIRTUE           ;  46
	const MON_DUNAMIS          ;  47
	const MON_DOMINION         ;  48
	const MON_OFANIM           ;  49
	const MON_CURIOTES         ;  4A
	const MON_GALGALIM         ;  4B
	const MON_SARIEL           ;  4C
	const MON_CHERUBIM         ;  4D
	const MON_SERAPHIM         ;  4E
	const MON_MERKABAH         ;  4F
	const MON_EGO              ;  50
	const MON_ARCHANGEL        ;  51
	const MON_SATAN            ;  52
	const MON_GNOME            ;  53
	const MON_PIXIE            ;  54
	const MON_YETI             ;  55
	const MON_HUMBABA          ;  56
	const MON_ISSUN_BOUSHI     ;  57
	const MON_RASETSU          ;  58
	const MON_ITSUMADE         ;  59
	const MON_GOLEM            ;  5A
	const MON_SYLPH            ;  5B
	const MON_RASETSU_LORD     ;  5C
	const MON_SKELETON         ;  5D
	const MON_NITANITA         ;  5E
	const MON_BIFURYUS         ;  5F
	const MON_GHOUL            ;  60
	const MON_TOUSHIN          ;  61
	const MON_SON_GOKU         ;  62
	const MON_ROBOT            ;  63
	const MON_DWARF            ;  64
	const MON_MUMMY            ;  65
	const MON_TROLL            ;  66
	const MON_BOOGEYMAN        ;  67
	const MON_YAMANBA          ;  68
	const MON_ONI              ;  69
	const MON_ANDROID          ;  6A
	const MON_DEVIKUN          ;  6B
	const MON_HECATONCHEIR     ;  6C
	const MON_GIRIMEKRA        ;  6D
	const MON_CALADBORG        ;  6E
	const MON_COUNT_SHEEP      ;  6F
	const MON_VETARA           ;  70
	const MON_CAIT_SITH        ;  71
	const MON_SANDMAN          ;  72
	const MON_UNDINE           ;  73
	const MON_PILLOW_SWAPPER   ;  74
	const MON_ONIBI            ;  75
	const MON_PHANTOM          ;  76
	const MON_RED_CAPE         ;  77
	const MON_VAMPIRE          ;  78
	const MON_MELISSA          ;  79
	const MON_INCUBUS          ;  7A
	const MON_TAPIR            ;  7B
	const MON_SUCCUBUS         ;  7C
	const MON_BANSHEE          ;  7D
	const MON_QUICKSILVER      ;  7E
	const MON_PERSONA          ;  7F
	const MON_LEGION           ;  80
	const MON_IFRIT            ;  81
	const MON_MOKOI            ;  82
	const MON_YATAGARASU       ;  83
	const MON_DULLAHAN         ;  84
	const MON_DOPPELGANGER     ;  85
	const MON_SILVERFOX        ;  86
	const MON_NIGHTMARE        ;  87
	const MON_KYUKI            ;  88
	const MON_NAMTAR           ;  89
	const MON_ANKOU            ;  8A
	const MON_NESSIE           ;  8B
	const MON_SAND_DRAGON      ;  8C
	const MON_MIZUCHI          ;  8D
	const MON_MAKARA           ;  8E
	const MON_SALAMANDER       ;  8F
	const MON_OTOHIME          ;  90
	const MON_BASILISK         ;  91
	const MON_FAFNEL           ;  92
	const MON_COCKATRICE       ;  93
	const MON_OROCHI           ;  94
	const MON_DAHAKA           ;  95
	const MON_CROM_CRUACH      ;  96
	const MON_CULEBRE          ;  97
	const MON_SEIRYU           ;  98
	const MON_WYVERN           ;  99
	const MON_YAMATANO_OROCHI  ;  9A
	const MON_NAGA             ;  9B
	const MON_VASUKI           ;  9C
	const MON_SVABNIR          ;  9D
	const MON_OURYU            ;  9E
	const MON_SEKIRYU          ;  AF
	const MON_YURUNG           ;  A0
	const MON_OUROBOROS        ;  A1
	const MON_ANANTA           ;  A2
	const MON_KOKURYU          ;  A3
	const MON_VAGET            ;  A4
	const MON_HAKURYU          ;  A5
	const MON_TINY_FROST       ;  A6
	const MON_RATATOSKR        ;  A7
	const MON_GARM             ;  A8
	const MON_YUKINKO          ;  A9
	const MON_JACK_FROST       ;  AA
	const MON_STRAWBERRY_FROST ;  AB
	const MON_JACK_LANTERN     ;  AC
	const MON_KAMAITACHI       ;  AD
	const MON_SNOW_WOMAN       ;  AE
	const MON_TUBEFOX          ;  AF
	const MON_ORTHROS          ;  B0
	const MON_CAT_FOOD         ;  B1
	const MON_FROST_ACE        ;  B2
	const MON_MYRMECOLEO       ;  B3
	const MON_TITANIA          ;  B4
	const MON_NINETAILED_FOX   ;  B5
	const MON_ZACCOUM          ;  B6
	const MON_KING_FROST       ;  B7
	const MON_HARPY            ;  B8
	const MON_CU_SITH          ;  B9
	const MON_MANDRAKE         ;  BA
	const MON_KIJIMUNA         ;  BB
	const MON_CHAOS            ;  BC
	const MON_TAOWN            ;  BD
	const MON_SIREN            ;  BE
	const MON_DAKKI            ;  BF
	const MON_TENGU            ;  C0
	const MON_MANTICORE        ;  C1
	const MON_PARAMECIUM       ;  C2
	const MON_MECCHY           ;  C3
	const MON_KOROPOKKUR       ;  C4
	const MON_SHOCK            ;  C5
	const MON_GURIGURI         ;  C6
	const MON_AGATHION         ;  C7
	const MON_WAIRA            ;  C8
	const MON_FAIRY            ;  C9
	const MON_INABA_BUNNY      ;  CA
	const MON_NACHT_COBALT     ;  CB
	const MON_NIDHOGGR         ;  CC
	const MON_KAPPA            ;  CD
	const MON_FRANKEN          ;  CE
	const MON_TAKUHI           ;  CF
	const MON_SNAPPY           ;  D0
	const MON_AIRAVATA         ;  D1
	const MON_KAICHI           ;  D2
	const MON_LYNX             ;  D3
	const MON_SKYLLA           ;  D4
	const MON_GANESHA          ;  D5
	const MON_SIMURGH          ;  D6
	const MON_CHARON           ;  D7
	const MON_HELLHOUND        ;  D8
	const MON_ODIN             ;  D9
	const MON_FRESBERK         ;  DA
	const MON_DIANA            ;  DB
	const MON_HEL              ;  DC
	const MON_BIBISANA         ;  DD
	const MON_VRITRA           ;  DE
	const MON_INDRA            ;  DF
	const MON_FENRIR           ;  E0
	const MON_ABADDON          ;  E1
	const MON_PAIMON           ;  E2
	const MON_SPHYNX           ;  E3
	const MON_ASMODEUS         ;  E4
	const MON_DEMOGORGON       ;  E5
	const MON_DEATH_SPHYNX     ;  E6
	const MON_BELIAL           ;  E7
	const MON_HELL_SPHYNX      ;  E8
	const MON_URIEL            ;  E9
	const MON_RAPHAEL          ;  EA
	const MON_LUCIFER          ;  EB
	const MON_AZEL             ;  EC
	const MON_MICHAEL          ;  ED
	const MON_NEO_SPHYNX       ;  EE
	const MON_HOSHIGAMI        ;  EF
	const MON_BERITH           ;  F0
	const MON_PHEGOR           ;  F1
	const MON_ZEBUL            ;  F2
	const MON_CERBEROS         ;  F3
	const MON_DEATH_CERBEROS   ;  F4
	const MON_HELL_CERBEROS    ;  F5
	const MON_KING_CERBEROS    ;  F6
	const MON_GRYPHON          ;  F7
	const MON_DEATH_GRYPHON    ;  F8
	const MON_HELL_GRYPHON     ;  F9
	const MON_KING_GRYPHON     ;  FA
	const MON_BEHEMOTH         ;  FB
	const MON_LEVIATHAN        ;  FC
	const MON_HORNED_DRAGON    ;  FD
	const MON_GABRIEL          ;  FE
	const MON_METATRON         ;  FF
IF DEF(SHIRO)
	const MON_CHIMERA          ; 100
	const MON_DEATH_CHIMERA    ; 101
	const MON_HELL_CHIMERA     ; 102
	const MON_KING_CHIMERA     ; 103
	const MON_PHOENIX          ; 104
	const MON_DEATH_PHOENIX    ; 105
	const MON_HELL_PHOENIX     ; 106
	const MON_NEO_PHOENIX      ; 107
	const MON_IMP              ; 108
	const MON_CUPID            ; 109
	const MON_RAGUEL           ; 10A
	const MON_NATHANIEL        ; 10B
	const MON_MIDHIR           ; 10C
	const MON_MOLOCH           ; 10D
	const MON_SETH             ; 10E
	const MON_STOLAS           ; 10F
	const MON_KALI             ; 110
	const MON_STRIBOG          ; 111
	const MON_VALKYRIE         ; 112
	const MON_DIAN_CECHT       ; 113
	const MON_SAMIGINA         ; 114
	const MON_BUG              ; 115
	const MON_HAG              ; 116
	const MON_LINDWURM         ; 117
	const MON_FURFUR           ; 118
	const MON_MURMUR           ; 119
	const MON_MARCHOCIAS       ; 11A
	const MON_VISHNU           ; 11B
	const MON_RA               ; 11C
	const MON_BRAN             ; 11D
	const MON_JASHIN           ; 11E
	const MON_MELON_FROST      ; 11F
	const MON_LEMON_FROST      ; 120
	const MON_FROST_TRIO       ; 121
	const MON_ALICE            ; 122
	const MON_DJINN            ; 123
	const MON_TANKORORIN       ; 124
	const MON_UMI_BOUZU        ; 125
	const MON_SHIVA            ; 126
	const MON_HANUMAN          ; 127
	const MON_ASTAROTH         ; 128
	const MON_ARIOCH           ; 129
	const MON_BACKBEARD        ; 12A
	const MON_OSHICHI          ; 12B
	const MON_CU_CHULAINN      ; 12C
	const MON_HIRUKO           ; 12D
	const MON_TIAMAT           ; 12E
	const MON_ISHTAR           ; 12F
	const MON_HADES            ; 130
	const MON_DAGON            ; 131
	const MON_ARTEMIS          ; 132
	const MON_TALOS            ; 133
	const MON_HOMUNCULUS       ; 134
	const MON_ZASHIKI_WARASHI  ; 135
	const MON_GOGMAGOG         ; 136
	const MON_KAMINARISAMA     ; 137
	const MON_OOKUNINUSHI      ; 138
	const MON_SOMA             ; 139
	const MON_IRON_KITSUNE     ; 13A
	const MON_KASHYAPA         ; 13B
	const MON_SICKLE_MONKEY    ; 13C
	const MON_HEART            ; 13D
	const MON_INDY             ; 13E
	const MON_SWEET            ; 13F
	const MON_AQUACLOUD        ; 140
	const MON_PLUTO            ; 141
	const MON_GREEN_MAN        ; 142
	const MON_FLOWER_KILLER    ; 143
	const MON_CHIRUCHIRU       ; 144
	const MON_VIKING           ; 145
	const MON_KIRUDANTE        ; 146
	const MON_LEMONCHI         ; 147
	const MON_MANEDANUKI       ; 148
	const MON_BLACK_BARON      ; 149
	const MON_COWARDLY_EGG     ; 14A
	const MON_MUSHROOM_PRIEST  ; 14B
	const MON_LOST             ; 14C
	const MON_SHADOW           ; 14D
	const MON_REQUIEM          ; 14E
	const MON_GILGAMESH        ; 14F
	const MON_DUMMY335         ; 150
	const MON_DUMMY336         ; 151
	const MON_DUMMY337         ; 152
	const MON_DUMMY338         ; 153
	const MON_DUMMY339         ; 154
	const MON_DUMMY340         ; 155
	const MON_DUMMY34１         ; 156
	const MON_DUMMY34２         ; 157
	const MON_DUMMY343         ; 158
	const MON_DUMMY344         ; 159
	const MON_DUMMY345         ; 15A
	const MON_DUMMY346         ; 15B
	const MON_DUMMY347         ; 15C
	const MON_DUMMY348         ; 15D
	const MON_DUMMY349         ; 15E
	const MON_DUMMY350         ; 15F
	const MON_DUMMY35１         ; 160
	const MON_DUMMY35２         ; 161
	const MON_DUMMY353         ; 162
	const MON_DUMMY354         ; 163
	const MON_DUMMY355         ; 164
	const MON_DUMMY356         ; 165
	const MON_DUMMY357         ; 166
	const MON_DUMMY358         ; 167
	const MON_DUMMY359         ; 168
ENDC
