
	charmap "０", $00
	charmap "１", $01
	charmap "２", $02
	charmap "３", $03
	charmap "４", $04
	charmap "５", $05
	charmap "６", $06
	charmap "７", $07
	charmap "８", $08
	charmap "９", $09
	charmap "＃", $0A ; string end marker
	charmap "ー", $15
	charmap "あ", $1E
	charmap "い", $1F
	charmap "う", $20
	charmap "え", $21
	charmap "お", $22
	charmap "か", $23
	charmap "き", $24
	charmap "く", $25
	charmap "け", $26
	charmap "こ", $27
	charmap "さ", $28
	charmap "し", $29
	charmap "す", $2A
	charmap "せ", $2B
	charmap "そ", $2C
	charmap "た", $2D
	charmap "ち", $2E
	charmap "つ", $2F
	charmap "て", $30
	charmap "と", $31
	charmap "な", $32
	charmap "に", $33
	charmap "ぬ", $34
	charmap "ね", $35
	charmap "の", $36
	charmap "は", $37
	charmap "ひ", $38
	charmap "ふ", $39
	charmap "へ", $3A
	charmap "ほ", $3B
	charmap "ま", $3C
	charmap "み", $3D
	charmap "む", $3E
	charmap "め", $3F
	charmap "も", $40
	charmap "や", $41
	charmap "ゆ", $42
	charmap "よ", $43
	charmap "ら", $44
	charmap "り", $45
	charmap "る", $46
	charmap "れ", $47
	charmap "ろ", $48
	charmap "わ", $49
	charmap "を", $4A
	charmap "ん", $4B
	charmap "ぁ", $4C
	charmap "ぃ", $4D
	charmap "ぅ", $4E
	charmap "ぇ", $4F
	charmap "ぉ", $50
	charmap "っ", $51
	charmap "ゃ", $52
	charmap "ゅ", $53
	charmap "ょ", $54
	charmap "ア", $55
	charmap "イ", $56
	charmap "ウ", $57
	charmap "エ", $58
	charmap "オ", $59
	charmap "カ", $5A
	charmap "キ", $5B
	charmap "ク", $5C
	charmap "ケ", $5D
	charmap "コ", $5E
	charmap "サ", $5F
	charmap "シ", $60
	charmap "ス", $61
	charmap "セ", $62
	charmap "ソ", $63
	charmap "タ", $64
	charmap "チ", $65
	charmap "ツ", $66
	charmap "テ", $67
	charmap "ト", $68
	charmap "ナ", $69
	charmap "ニ", $6A
	charmap "ヌ", $6B
	charmap "ネ", $6C
	charmap "ノ", $6D
	charmap "ハ", $6E
	charmap "ヒ", $6F
	charmap "フ", $70
	charmap "ヘ", $71
	charmap "ホ", $72
	charmap "マ", $73
	charmap "ミ", $74
	charmap "ム", $75
	charmap "メ", $76
	charmap "モ", $77
	charmap "ヤ", $78
	charmap "ユ", $79
	charmap "ヨ", $7A
	charmap "ラ", $7B
	charmap "リ", $7C
	charmap "ル", $7D
	charmap "レ", $7E
	charmap "ロ", $7F
	charmap "ワ", $80
	charmap "ヲ", $81
	charmap "ン", $82
	charmap "ァ", $83
	charmap "ィ", $84
	charmap "ゥ", $85
	charmap "ェ", $86
	charmap "ォ", $87
	charmap "ッ", $88
	charmap "ャ", $89
	charmap "ュ", $8A
	charmap "ョ", $8B
	charmap "が", $8C
	charmap "ぎ", $8D
	charmap "ぐ", $8E
	charmap "げ", $8F
	charmap "ご", $90
	charmap "ざ", $91
	charmap "じ", $92
	charmap "ず", $93
	charmap "ぜ", $94
	charmap "ぞ", $95
	charmap "だ", $96
	charmap "ぢ", $97
	charmap "づ", $98
	charmap "で", $99
	charmap "ど", $9A
	charmap "ば", $9B
	charmap "び", $9C
	charmap "ぶ", $9D
	charmap "べ", $9E
	charmap "ぼ", $9F
	charmap "ぱ", $A0
	charmap "ぴ", $A1
	charmap "ぷ", $A2
	charmap "ぺ", $A3
	charmap "ぽ", $A4
	charmap "ガ", $A5
	charmap "ギ", $A6
	charmap "グ", $A7
	charmap "ゲ", $A8
	charmap "ゴ", $A9
	charmap "ザ", $AA
	charmap "ジ", $AB
	charmap "ズ", $AC
	charmap "ゼ", $AD
	charmap "ゾ", $AE
	charmap "ダ", $AF
	charmap "ヂ", $B0
	charmap "ヅ", $B1
	charmap "デ", $B2
	charmap "ド", $B3
	charmap "バ", $B4
	charmap "ビ", $B5
	charmap "ブ", $B6
	charmap "ベ", $B7
	charmap "ボ", $B8
	charmap "パ", $B9
	charmap "ピ", $BA
	charmap "プ", $BB
	charmap "ペ", $BC
	charmap "ポ", $BD
	charmap "ヴ", $BE
	charmap "。", $BF
	charmap "・", $C8